/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardRoleStatusMappingIndexRouteImport } from './routes/_authenticated/dashboard/roleStatusMapping/index'
import { Route as AuthenticatedDashboardRoleStatusAccessIndexRouteImport } from './routes/_authenticated/dashboard/roleStatusAccess/index'
import { Route as AuthenticatedDashboardRoleIndexRouteImport } from './routes/_authenticated/dashboard/role/index'
import { Route as AuthenticatedDashboardReleaseAppIndexRouteImport } from './routes/_authenticated/dashboard/releaseApp/index'
import { Route as AuthenticatedDashboardOrderStatusIndexRouteImport } from './routes/_authenticated/dashboard/orderStatus/index'
import { Route as AuthenticatedDashboardLabelIndexRouteImport } from './routes/_authenticated/dashboard/label/index'
import { Route as AuthenticatedDashboardCountryIndexRouteImport } from './routes/_authenticated/dashboard/country/index'
import { Route as AuthenticatedDashboardAdminsIndexRouteImport } from './routes/_authenticated/dashboard/admins/index'
import { Route as AuthenticatedDashboardEmailSettingSmtpIndexRouteImport } from './routes/_authenticated/dashboard/emailSetting/smtp/index'
import { Route as AuthenticatedDashboardEmailSettingEmailTemplatesIndexRouteImport } from './routes/_authenticated/dashboard/emailSetting/emailTemplates/index'
import { Route as AuthenticatedDashboardEmailSettingEmailEjsIndexRouteImport } from './routes/_authenticated/dashboard/emailSetting/emailEjs/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRoleStatusMappingIndexRoute =
  AuthenticatedDashboardRoleStatusMappingIndexRouteImport.update({
    id: '/roleStatusMapping/',
    path: '/roleStatusMapping/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRoleStatusAccessIndexRoute =
  AuthenticatedDashboardRoleStatusAccessIndexRouteImport.update({
    id: '/roleStatusAccess/',
    path: '/roleStatusAccess/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRoleIndexRoute =
  AuthenticatedDashboardRoleIndexRouteImport.update({
    id: '/role/',
    path: '/role/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardReleaseAppIndexRoute =
  AuthenticatedDashboardReleaseAppIndexRouteImport.update({
    id: '/releaseApp/',
    path: '/releaseApp/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOrderStatusIndexRoute =
  AuthenticatedDashboardOrderStatusIndexRouteImport.update({
    id: '/orderStatus/',
    path: '/orderStatus/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardLabelIndexRoute =
  AuthenticatedDashboardLabelIndexRouteImport.update({
    id: '/label/',
    path: '/label/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCountryIndexRoute =
  AuthenticatedDashboardCountryIndexRouteImport.update({
    id: '/country/',
    path: '/country/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAdminsIndexRoute =
  AuthenticatedDashboardAdminsIndexRouteImport.update({
    id: '/admins/',
    path: '/admins/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardEmailSettingSmtpIndexRoute =
  AuthenticatedDashboardEmailSettingSmtpIndexRouteImport.update({
    id: '/emailSetting/smtp/',
    path: '/emailSetting/smtp/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardEmailSettingEmailTemplatesIndexRoute =
  AuthenticatedDashboardEmailSettingEmailTemplatesIndexRouteImport.update({
    id: '/emailSetting/emailTemplates/',
    path: '/emailSetting/emailTemplates/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardEmailSettingEmailEjsIndexRoute =
  AuthenticatedDashboardEmailSettingEmailEjsIndexRouteImport.update({
    id: '/emailSetting/emailEjs/',
    path: '/emailSetting/emailEjs/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admins/': typeof AuthenticatedDashboardAdminsIndexRoute
  '/dashboard/country/': typeof AuthenticatedDashboardCountryIndexRoute
  '/dashboard/label/': typeof AuthenticatedDashboardLabelIndexRoute
  '/dashboard/orderStatus/': typeof AuthenticatedDashboardOrderStatusIndexRoute
  '/dashboard/releaseApp/': typeof AuthenticatedDashboardReleaseAppIndexRoute
  '/dashboard/role/': typeof AuthenticatedDashboardRoleIndexRoute
  '/dashboard/roleStatusAccess/': typeof AuthenticatedDashboardRoleStatusAccessIndexRoute
  '/dashboard/roleStatusMapping/': typeof AuthenticatedDashboardRoleStatusMappingIndexRoute
  '/dashboard/emailSetting/emailEjs/': typeof AuthenticatedDashboardEmailSettingEmailEjsIndexRoute
  '/dashboard/emailSetting/emailTemplates/': typeof AuthenticatedDashboardEmailSettingEmailTemplatesIndexRoute
  '/dashboard/emailSetting/smtp/': typeof AuthenticatedDashboardEmailSettingSmtpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admins': typeof AuthenticatedDashboardAdminsIndexRoute
  '/dashboard/country': typeof AuthenticatedDashboardCountryIndexRoute
  '/dashboard/label': typeof AuthenticatedDashboardLabelIndexRoute
  '/dashboard/orderStatus': typeof AuthenticatedDashboardOrderStatusIndexRoute
  '/dashboard/releaseApp': typeof AuthenticatedDashboardReleaseAppIndexRoute
  '/dashboard/role': typeof AuthenticatedDashboardRoleIndexRoute
  '/dashboard/roleStatusAccess': typeof AuthenticatedDashboardRoleStatusAccessIndexRoute
  '/dashboard/roleStatusMapping': typeof AuthenticatedDashboardRoleStatusMappingIndexRoute
  '/dashboard/emailSetting/emailEjs': typeof AuthenticatedDashboardEmailSettingEmailEjsIndexRoute
  '/dashboard/emailSetting/emailTemplates': typeof AuthenticatedDashboardEmailSettingEmailTemplatesIndexRoute
  '/dashboard/emailSetting/smtp': typeof AuthenticatedDashboardEmailSettingSmtpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admins/': typeof AuthenticatedDashboardAdminsIndexRoute
  '/_authenticated/dashboard/country/': typeof AuthenticatedDashboardCountryIndexRoute
  '/_authenticated/dashboard/label/': typeof AuthenticatedDashboardLabelIndexRoute
  '/_authenticated/dashboard/orderStatus/': typeof AuthenticatedDashboardOrderStatusIndexRoute
  '/_authenticated/dashboard/releaseApp/': typeof AuthenticatedDashboardReleaseAppIndexRoute
  '/_authenticated/dashboard/role/': typeof AuthenticatedDashboardRoleIndexRoute
  '/_authenticated/dashboard/roleStatusAccess/': typeof AuthenticatedDashboardRoleStatusAccessIndexRoute
  '/_authenticated/dashboard/roleStatusMapping/': typeof AuthenticatedDashboardRoleStatusMappingIndexRoute
  '/_authenticated/dashboard/emailSetting/emailEjs/': typeof AuthenticatedDashboardEmailSettingEmailEjsIndexRoute
  '/_authenticated/dashboard/emailSetting/emailTemplates/': typeof AuthenticatedDashboardEmailSettingEmailTemplatesIndexRoute
  '/_authenticated/dashboard/emailSetting/smtp/': typeof AuthenticatedDashboardEmailSettingSmtpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login/'
    | '/dashboard/'
    | '/dashboard/admins/'
    | '/dashboard/country/'
    | '/dashboard/label/'
    | '/dashboard/orderStatus/'
    | '/dashboard/releaseApp/'
    | '/dashboard/role/'
    | '/dashboard/roleStatusAccess/'
    | '/dashboard/roleStatusMapping/'
    | '/dashboard/emailSetting/emailEjs/'
    | '/dashboard/emailSetting/emailTemplates/'
    | '/dashboard/emailSetting/smtp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/admins'
    | '/dashboard/country'
    | '/dashboard/label'
    | '/dashboard/orderStatus'
    | '/dashboard/releaseApp'
    | '/dashboard/role'
    | '/dashboard/roleStatusAccess'
    | '/dashboard/roleStatusMapping'
    | '/dashboard/emailSetting/emailEjs'
    | '/dashboard/emailSetting/emailTemplates'
    | '/dashboard/emailSetting/smtp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/login/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admins/'
    | '/_authenticated/dashboard/country/'
    | '/_authenticated/dashboard/label/'
    | '/_authenticated/dashboard/orderStatus/'
    | '/_authenticated/dashboard/releaseApp/'
    | '/_authenticated/dashboard/role/'
    | '/_authenticated/dashboard/roleStatusAccess/'
    | '/_authenticated/dashboard/roleStatusMapping/'
    | '/_authenticated/dashboard/emailSetting/emailEjs/'
    | '/_authenticated/dashboard/emailSetting/emailTemplates/'
    | '/_authenticated/dashboard/emailSetting/smtp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/roleStatusMapping/': {
      id: '/_authenticated/dashboard/roleStatusMapping/'
      path: '/roleStatusMapping'
      fullPath: '/dashboard/roleStatusMapping/'
      preLoaderRoute: typeof AuthenticatedDashboardRoleStatusMappingIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/roleStatusAccess/': {
      id: '/_authenticated/dashboard/roleStatusAccess/'
      path: '/roleStatusAccess'
      fullPath: '/dashboard/roleStatusAccess/'
      preLoaderRoute: typeof AuthenticatedDashboardRoleStatusAccessIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/role/': {
      id: '/_authenticated/dashboard/role/'
      path: '/role'
      fullPath: '/dashboard/role/'
      preLoaderRoute: typeof AuthenticatedDashboardRoleIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/releaseApp/': {
      id: '/_authenticated/dashboard/releaseApp/'
      path: '/releaseApp'
      fullPath: '/dashboard/releaseApp/'
      preLoaderRoute: typeof AuthenticatedDashboardReleaseAppIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/orderStatus/': {
      id: '/_authenticated/dashboard/orderStatus/'
      path: '/orderStatus'
      fullPath: '/dashboard/orderStatus/'
      preLoaderRoute: typeof AuthenticatedDashboardOrderStatusIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/label/': {
      id: '/_authenticated/dashboard/label/'
      path: '/label'
      fullPath: '/dashboard/label/'
      preLoaderRoute: typeof AuthenticatedDashboardLabelIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/country/': {
      id: '/_authenticated/dashboard/country/'
      path: '/country'
      fullPath: '/dashboard/country/'
      preLoaderRoute: typeof AuthenticatedDashboardCountryIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/admins/': {
      id: '/_authenticated/dashboard/admins/'
      path: '/admins'
      fullPath: '/dashboard/admins/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/emailSetting/smtp/': {
      id: '/_authenticated/dashboard/emailSetting/smtp/'
      path: '/emailSetting/smtp'
      fullPath: '/dashboard/emailSetting/smtp/'
      preLoaderRoute: typeof AuthenticatedDashboardEmailSettingSmtpIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/emailSetting/emailTemplates/': {
      id: '/_authenticated/dashboard/emailSetting/emailTemplates/'
      path: '/emailSetting/emailTemplates'
      fullPath: '/dashboard/emailSetting/emailTemplates/'
      preLoaderRoute: typeof AuthenticatedDashboardEmailSettingEmailTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/emailSetting/emailEjs/': {
      id: '/_authenticated/dashboard/emailSetting/emailEjs/'
      path: '/emailSetting/emailEjs'
      fullPath: '/dashboard/emailSetting/emailEjs/'
      preLoaderRoute: typeof AuthenticatedDashboardEmailSettingEmailEjsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminsIndexRoute: typeof AuthenticatedDashboardAdminsIndexRoute
  AuthenticatedDashboardCountryIndexRoute: typeof AuthenticatedDashboardCountryIndexRoute
  AuthenticatedDashboardLabelIndexRoute: typeof AuthenticatedDashboardLabelIndexRoute
  AuthenticatedDashboardOrderStatusIndexRoute: typeof AuthenticatedDashboardOrderStatusIndexRoute
  AuthenticatedDashboardReleaseAppIndexRoute: typeof AuthenticatedDashboardReleaseAppIndexRoute
  AuthenticatedDashboardRoleIndexRoute: typeof AuthenticatedDashboardRoleIndexRoute
  AuthenticatedDashboardRoleStatusAccessIndexRoute: typeof AuthenticatedDashboardRoleStatusAccessIndexRoute
  AuthenticatedDashboardRoleStatusMappingIndexRoute: typeof AuthenticatedDashboardRoleStatusMappingIndexRoute
  AuthenticatedDashboardEmailSettingEmailEjsIndexRoute: typeof AuthenticatedDashboardEmailSettingEmailEjsIndexRoute
  AuthenticatedDashboardEmailSettingEmailTemplatesIndexRoute: typeof AuthenticatedDashboardEmailSettingEmailTemplatesIndexRoute
  AuthenticatedDashboardEmailSettingSmtpIndexRoute: typeof AuthenticatedDashboardEmailSettingSmtpIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAdminsIndexRoute:
      AuthenticatedDashboardAdminsIndexRoute,
    AuthenticatedDashboardCountryIndexRoute:
      AuthenticatedDashboardCountryIndexRoute,
    AuthenticatedDashboardLabelIndexRoute:
      AuthenticatedDashboardLabelIndexRoute,
    AuthenticatedDashboardOrderStatusIndexRoute:
      AuthenticatedDashboardOrderStatusIndexRoute,
    AuthenticatedDashboardReleaseAppIndexRoute:
      AuthenticatedDashboardReleaseAppIndexRoute,
    AuthenticatedDashboardRoleIndexRoute: AuthenticatedDashboardRoleIndexRoute,
    AuthenticatedDashboardRoleStatusAccessIndexRoute:
      AuthenticatedDashboardRoleStatusAccessIndexRoute,
    AuthenticatedDashboardRoleStatusMappingIndexRoute:
      AuthenticatedDashboardRoleStatusMappingIndexRoute,
    AuthenticatedDashboardEmailSettingEmailEjsIndexRoute:
      AuthenticatedDashboardEmailSettingEmailEjsIndexRoute,
    AuthenticatedDashboardEmailSettingEmailTemplatesIndexRoute:
      AuthenticatedDashboardEmailSettingEmailTemplatesIndexRoute,
    AuthenticatedDashboardEmailSettingSmtpIndexRoute:
      AuthenticatedDashboardEmailSettingSmtpIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
