/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardRoleIndexRouteImport } from './routes/_authenticated/dashboard/role/index'
import { Route as AuthenticatedDashboardOrderStatusIndexRouteImport } from './routes/_authenticated/dashboard/orderStatus/index'
import { Route as AuthenticatedDashboardLabelIndexRouteImport } from './routes/_authenticated/dashboard/label/index'
import { Route as AuthenticatedDashboardCountryIndexRouteImport } from './routes/_authenticated/dashboard/country/index'
import { Route as AuthenticatedDashboardAdminsIndexRouteImport } from './routes/_authenticated/dashboard/admins/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardRoleIndexRoute =
  AuthenticatedDashboardRoleIndexRouteImport.update({
    id: '/role/',
    path: '/role/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardOrderStatusIndexRoute =
  AuthenticatedDashboardOrderStatusIndexRouteImport.update({
    id: '/orderStatus/',
    path: '/orderStatus/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardLabelIndexRoute =
  AuthenticatedDashboardLabelIndexRouteImport.update({
    id: '/label/',
    path: '/label/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCountryIndexRoute =
  AuthenticatedDashboardCountryIndexRouteImport.update({
    id: '/country/',
    path: '/country/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardAdminsIndexRoute =
  AuthenticatedDashboardAdminsIndexRouteImport.update({
    id: '/admins/',
    path: '/admins/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admins/': typeof AuthenticatedDashboardAdminsIndexRoute
  '/dashboard/country/': typeof AuthenticatedDashboardCountryIndexRoute
  '/dashboard/label/': typeof AuthenticatedDashboardLabelIndexRoute
  '/dashboard/orderStatus/': typeof AuthenticatedDashboardOrderStatusIndexRoute
  '/dashboard/role/': typeof AuthenticatedDashboardRoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admins': typeof AuthenticatedDashboardAdminsIndexRoute
  '/dashboard/country': typeof AuthenticatedDashboardCountryIndexRoute
  '/dashboard/label': typeof AuthenticatedDashboardLabelIndexRoute
  '/dashboard/orderStatus': typeof AuthenticatedDashboardOrderStatusIndexRoute
  '/dashboard/role': typeof AuthenticatedDashboardRoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admins/': typeof AuthenticatedDashboardAdminsIndexRoute
  '/_authenticated/dashboard/country/': typeof AuthenticatedDashboardCountryIndexRoute
  '/_authenticated/dashboard/label/': typeof AuthenticatedDashboardLabelIndexRoute
  '/_authenticated/dashboard/orderStatus/': typeof AuthenticatedDashboardOrderStatusIndexRoute
  '/_authenticated/dashboard/role/': typeof AuthenticatedDashboardRoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login/'
    | '/dashboard/'
    | '/dashboard/admins/'
    | '/dashboard/country/'
    | '/dashboard/label/'
    | '/dashboard/orderStatus/'
    | '/dashboard/role/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/admins'
    | '/dashboard/country'
    | '/dashboard/label'
    | '/dashboard/orderStatus'
    | '/dashboard/role'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/login/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admins/'
    | '/_authenticated/dashboard/country/'
    | '/_authenticated/dashboard/label/'
    | '/_authenticated/dashboard/orderStatus/'
    | '/_authenticated/dashboard/role/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/role/': {
      id: '/_authenticated/dashboard/role/'
      path: '/role'
      fullPath: '/dashboard/role/'
      preLoaderRoute: typeof AuthenticatedDashboardRoleIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/orderStatus/': {
      id: '/_authenticated/dashboard/orderStatus/'
      path: '/orderStatus'
      fullPath: '/dashboard/orderStatus/'
      preLoaderRoute: typeof AuthenticatedDashboardOrderStatusIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/label/': {
      id: '/_authenticated/dashboard/label/'
      path: '/label'
      fullPath: '/dashboard/label/'
      preLoaderRoute: typeof AuthenticatedDashboardLabelIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/country/': {
      id: '/_authenticated/dashboard/country/'
      path: '/country'
      fullPath: '/dashboard/country/'
      preLoaderRoute: typeof AuthenticatedDashboardCountryIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/admins/': {
      id: '/_authenticated/dashboard/admins/'
      path: '/admins'
      fullPath: '/dashboard/admins/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminsIndexRoute: typeof AuthenticatedDashboardAdminsIndexRoute
  AuthenticatedDashboardCountryIndexRoute: typeof AuthenticatedDashboardCountryIndexRoute
  AuthenticatedDashboardLabelIndexRoute: typeof AuthenticatedDashboardLabelIndexRoute
  AuthenticatedDashboardOrderStatusIndexRoute: typeof AuthenticatedDashboardOrderStatusIndexRoute
  AuthenticatedDashboardRoleIndexRoute: typeof AuthenticatedDashboardRoleIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardAdminsIndexRoute:
      AuthenticatedDashboardAdminsIndexRoute,
    AuthenticatedDashboardCountryIndexRoute:
      AuthenticatedDashboardCountryIndexRoute,
    AuthenticatedDashboardLabelIndexRoute:
      AuthenticatedDashboardLabelIndexRoute,
    AuthenticatedDashboardOrderStatusIndexRoute:
      AuthenticatedDashboardOrderStatusIndexRoute,
    AuthenticatedDashboardRoleIndexRoute: AuthenticatedDashboardRoleIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
